[project]
name = "poa-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-ollama>=0.2.0",
    "langchain>=0.3.7",
    "matplotlib>=3.9.2",
    "tqdm>=4.67.0",
]
